module.exports = {
  globals: {
    'ts-jest': {
      tsconfig: './tsconfig.json',
      diagnostics: true,
    },
  },
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.+(ts|tsx|js)', '**/?(*.)+(spec|test).+(ts|tsx|js)'],
  setupFilesAfterEnv: ['<rootDir>/src/setupTests.ts'],
  transform: {
    '^.+\\.(ts|tsx)$': 'ts-jest',
    '^.+\\.svg$': 'svg-jest',
    '^.+\\.less': 'jest-transform-stub',
  },
  moduleNameMapper: {
    '^.+\\.css': 'identity-obj-proxy',
    '@assets/(.*)': '<rootDir>/src/assets/$1',
    '@assets': '<rootDir>/src/assets',
    '@context/(.*)': '<rootDir>/src/context/$1',
    '@context': '<rootDir>/src/context',
    '@hoc/(.*)': '<rootDir>/src/util/hoc/$1',
    '@hoc': '<rootDir>/src/util/hoc',
    '@layout/(.*)': '<rootDir>/src/layout/$1',
    '@layout': '<rootDir>/src/layout',
    '@hooks/(.*)': '<rootDir>/src/util/hooks/$1',
    '@hooks': '<rootDir>/src/util/hooks',
    '@pages/(.*)': '<rootDir>/src/pages/$1',
    '@pages': '<rootDir>/src/pages/',
    '@parts/(.*)': '<rootDir>/src/parts/$1',
    '@parts': '<rootDir>/src/parts/',
    '@styles/(.*)': '<rootDir>/src/styles/$1',
    '@styles': '<rootDir>/src/styles/',
    '@config': '<rootDir>/src/config',
    '@i18n/(.*)': '<rootDir>/src/i18n/$1',
    '@i18n': '<rootDir>/src/i18n',
    '@router/(.*)': '<rootDir>/src/router/$1',
    '@router': '<rootDir>/src/router',
    '@domain/(.*)': '<rootDir>/src/domain/$1',
    '@domain': '<rootDir>/src/domain',
    '@utils/(.*)': '<rootDir>/src/utils/$1',
    '@utils': '<rootDir>/src/utils',
    '@theme/(.*)': '<rootDir>/src/theme/$1',
    '@theme': '<rootDir>/src/theme',
    '@providers/(.*)': '<rootDir>/src/providers/$1',
    '@providers': '<rootDir>/src/providers',
  },
  modulePathIgnorePatterns: ['node_modules', '<rootDir>/src/app.less'],
};
